services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
      - /app/__pycache__
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
    command: ["python", "app.py"]
    stdin_open: true
    tty: true